const OrdersActionTypes = {
	ADD_NEW_ORDER_SUCCESS: 'order/ADD_NEW_ORDER_SUCCESS',
	ADD_NEW_ORDER_PENDING: 'order/ADD_NEW_ORDER_PENDING',
	ADD_NEW_ORDER_FAILED: 'order/ADD_NEW_ORDER_FAILED',
	FETCH_ALL_ORDERS_SUCCESS: 'order/FETCH_ALL_ORDERS_SUCCESS',
	FETCH_ALL_ORDERS_PENDING: 'order/FETCH_ALL_ORDERS_PENDING',
	FILTER_ORDERS_BY_STATUS: 'order/FILTER_ORDERS_BY_STATUS',
	SEARCH_ORDERS_BY_SERVICE_SUCCESS: 'order/SEARCH_ORDERS_BY_SERVICE_SUCCESS',
	SEARCH_ORDERS_BY_SERVICE_FAILED: 'order/SEARCH_ORDERS_BY_SERVICE_FAILED',
	ADD_MASS_ORDERS_SUCCESS: 'order/ADD_MASS_ORDERS_SUCCESS',
	ADD_MASS_ORDERS_PENDING: 'order/ADD_MASS_ORDERS_PENDING',
	ADD_MASS_ORDERS_FAILED: 'order/ADD_MASS_ORDERS_FAILED',
	RESET_ORDERS_STATUS: 'order/RESET_ORDERS_STATUS',
};

export default OrdersActionTypes;